config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
    get "friends", on: :collection
  end

  resources :favorites
  resources :notes do
    collection do
      post :preview
    end
  end

  resources :teases

  resources :topics do
    resources :notes, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  end

  resources :follow_requests do
    member do
      patch :accept
    end
    collection do
      get :approved_requests
    end
  end

  get "tools", to: "pages#tools"
  get "navigate", to: "pages#navigate", as: :navigate

  root "home#index"

  resources :topics do
    member do
      post :share
    end
  end

  resources :topics do
    member do
      post :share
    end
  end

  get "search", to: "search#index"

  get "tools", to: "pages#tools"

  resources :favorites, only: [] do
    post "toggle", on: :collection
  end

  # config/routes.rb
  resources :notes do
    collection do
      post :word_count
    end
  end
end

app/models/favorite.rb
# == Schema Information
#
# Table name: favorites
#
#  id               :bigint           not null, primary key
#  favoritable_type :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  favoritable_id   :bigint
#  note_id          :integer
#  topic_id         :bigint
#  user_id          :bigint           not null
#
# Indexes
#
#  index_favorites_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :favoritable, polymorphic: true

  belongs_to :note, optional: true
  belongs_to :topic, optional: true
  belongs_to :user

  validates :user_id, presence: true
  validates :favoritable_id, presence: true
  validates :favoritable_type, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def toggle
    favoritable = find_favoritable
    favorite = current_user.favorites.find_by(favoritable: favoritable)

    if favorite
      favorite.destroy
      @favorite_status = false
    else
      current_user.favorites.create(favoritable: favoritable)
      @favorite_status = true
    end

    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.js   # This will render `toggle.js.erb`
    end
  end

  private

  def find_favoritable
    if params[:favoritable_type] == "Topic"
      Topic.find(params[:favoritable_id])
    elsif params[:favoritable_type] == "Note"
      Note.find(params[:favoritable_id])
    else
      raise "Unknown favoritable type"
    end
  end
end

app/views/favorites/_favorite.html.erb
<div id="<%= dom_id favorite %>">
  <p>
    <strong>Note:</strong>
    <%= favorite.note_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= favorite.user_id %>
  </p>

</div>

app/views/favorites/_form.html.erb
<%= form_with(model: favorite) do |form| %>
  <% if favorite.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
        <% favorite.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :note_id, style: "display: block" %>
    <%= form.number_field :note_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render "form", favorite: @favorite %>

<br>

<div>
  <%= link_to "Show this favorite", @favorite %> |
  <%= link_to "Back to favorites", favorites_path %>
</div>

app/views/favorites/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Favorites</h1>

<div id="favorites">
  <% @favorites.each do |favorite| %>
    <%= render favorite %>
    <p>
      <%= link_to "Show this favorite", favorite %>
    </p>
  <% end %>
</div>

<%= link_to "New favorite", new_favorite_path %>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render "form", favorite: @favorite %>

<br>

<div>
  <%= link_to "Back to favorites", favorites_path %>
</div>

app/views/favorites/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @favorite %>

<div>
  <%= link_to "Edit this favorite", edit_favorite_path(@favorite) %> |
  <%= link_to "Back to favorites", favorites_path %>

  <%= button_to "Destroy this favorite", @favorite, method: :delete %>
</div>

app/views/favorites/toggle.js.erb
<% if @favorite_status %>
  $("#star-icon-<%= params[:favoritable_id] %>").removeClass("fa-regular").addClass("fa-solid");
<% else %>
  $("#star-icon-<%= params[:favoritable_id] %>").removeClass("fa-solid").addClass("fa-regular");
<% end %>